import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Button } from '../common/Button';
import { Menu, X } from 'lucide-react';
import { useState } from 'react';
export function Navbar() {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsx("nav", { className: "bg-white shadow-sm sticky top-0 z-50", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-br from-blue-600 to-blue-700 rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-xl", children: "S" }) }), _jsx("span", { className: "text-2xl font-bold bg-gradient-to-r from-blue-600 to-blue-700 bg-clip-text text-transparent", children: "SupplySense" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-8", children: [_jsx("a", { href: "#features", className: "text-gray-600 hover:text-gray-900 font-medium transition", children: "Features" }), _jsx("a", { href: "#pricing", className: "text-gray-600 hover:text-gray-900 font-medium transition", children: "Pricing" }), _jsx("a", { href: "#payment", className: "text-gray-600 hover:text-gray-900 font-medium transition", children: "Payment" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-4", children: [_jsx(Link, { to: "/login", children: _jsx(Button, { variant: "secondary", size: "sm", children: "Login" }) }), _jsx(Link, { to: "/register", children: _jsx(Button, { size: "sm", children: "Get Started" }) })] }), _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "md:hidden p-2 hover:bg-gray-100 rounded-lg", children: isOpen ? _jsx(X, { size: 24 }) : _jsx(Menu, { size: 24 }) })] }), isOpen && (_jsxs("div", { className: "md:hidden pb-4 space-y-3", children: [_jsx("a", { href: "#features", className: "block px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg", children: "Features" }), _jsx("a", { href: "#pricing", className: "block px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg", children: "Pricing" }), _jsx("a", { href: "#payment", className: "block px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg", children: "Payment" }), _jsxs("div", { className: "flex flex-col gap-2 px-4", children: [_jsx(Link, { to: "/login", className: "w-full", children: _jsx(Button, { variant: "secondary", size: "sm", className: "w-full", children: "Login" }) }), _jsx(Link, { to: "/register", className: "w-full", children: _jsx(Button, { size: "sm", className: "w-full", children: "Get Started" }) })] })] }))] }) }));
}
